### ISSUE TITLE
Restructure website

### ISSUE THREAD

**Issue by NoraLoose** [leap-stc/ClimSim#15]
In response to the NeurIPS reviewers, we will improve the website as follows:

- [ ] Break website up into several pages
- [ ] Add a sidebar for easy navigation
- [ ] Include "Quick start guide" and demo notebooks

I should be able to get this done by tomorrow.

**Comment by NoraLoose** [comment]
Resolving this issue will also solve issue #8.

**Comment by NoraLoose** [comment]
Question for @jerrylin96 and others: Are the demo notebooks meant to be included on the documentation website?

The table of contents suggests so:

https://github.com/leap-stc/ClimSim/blob/f7d092cbaf57d79d47fa56dc0fd3e00a391da696/website/_toc.yml#L8-L10

Note that the 3 demo notebooks do not show up because they live outside of the `website` directory. I can make them show up, if that is the intention.

**Comment by NoraLoose** [comment]
If the demo notebooks are meant to appear on the documentation website, maybe they should be cleaned up a little bit?

**Comment by cisaacstern** [comment]
I'll defer to @jerrylin96 of course, but to me it seems like including the demo notebooks on the website is a nice value-add for the website. As discussed in the meeting, otherwise the website is "just" the README. So I'd be 👍 on including them.
