### ISSUE TITLE
Create public leaderboard for online competition

### ISSUE THREAD

**Issue by jerrylin96** [leap-stc/ClimSim#37]
This will make use of our to-date held-out temporally disjoint test set. Scoring dataset was uploaded to HuggingFace for reproducibility purposes.

**Comment by NoraLoose** [comment]
Should this go on the website @jerrylin96?

**Comment by NoraLoose** [comment]
Can you provide a little bit more background on the online competition? Is the plan similar to https://www.iarai.ac.at/weather4cast/challenge/?
