### ISSUE TITLE
Add deep copy method to data_utils

### ISSUE THREAD

**Issue by jerrylin96** [leap-stc/ClimSim#40]
We want the ability to copy an object and change some of the attributes of the new object without interfering with the old object. @cisaacstern for visibility

**Comment by cisaacstern** [comment]
@jerrylin96 could you provide an example of the use case for this?

My sense is that adding a deep copy method to a user defined class in Python is somewhat of an anti-pattern. It's possible that we can achieve the same goal by factoring data_utils into multiple objects, but hard to say for sure before seeing the specific use case.
