### ISSUE TITLE
Can the directory `misc` be deleted?

### ISSUE THREAD

**Issue by NoraLoose** [leap-stc/ClimSim#43]
The directory `misc/` seems to only contain one notebook, whose name `_OLD.ipynb` suggests that it is outdated. Can we remove this notebook and the directory `misc/`?

**Comment by sungdukyu** [comment]
@NoraLoose That's my notebook for generating figures in the manuscript. It's OLD as the filename indicates. I made several updates to include more figures during the revision period. 

tldr: safe to delete the file and the directory!

**Comment by cisaacstern** [comment]
🧹 🧼 loving this cleanup!

**Comment by NoraLoose** [comment]
Great, thanks @sungdukyu!
