### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by NoraLoose** [leap-stc/ClimSim#49]
Add community guidelines to README and website. Something similar to:

> Additional issues from community researchers wishing to build off ClimSim or make use of our tools are welcome and can be raised using the GitHub issues page (preferred) or by directly emailing ClimSim maintainers.

**Comment by NoraLoose** [comment]
@jerrylin96 just added this to the README.

Jerry, would you mind creating a PR next time (rather than pushing directly to the main branch) so we can keep track of our progress and minimize merging conflicts with PRs in progress? Thanks!

**Comment by cisaacstern** [comment]
@jerrylin96 +1000% let's please try to use PRs going forward, this is actually getting palpably difficult to collaborate on without PRs for every change to `main`. 🙏

**Comment by NoraLoose** [comment]
Community guidelines are now found on the website at https://leap-stc.github.io/ClimSim/CONTRIBUTING.html.
