### ISSUE TITLE
Clean up evaluation notebooks

### ISSUE THREAD

**Issue by NoraLoose** [leap-stc/ClimSim#58]
The evaluation notebooks (as well as the demo notebooks) are now rendered on the website. I suggest to remove all cells below the figure in [this notebook](https://leap-stc.github.io/ClimSim/evaluation/main_figure_generation.html) until there is code for Figures 2-4.

**Comment by jerrylin96** [comment]
Done

**Comment by NoraLoose** [comment]
@jerrylin96 I would appreciate it if you could leave PRs for review by others. Especially PRs that change the website. Thank you! Please give me a thumbs-up whenever you read this message because I'm not sure if you get github notifications.
