### ISSUE TITLE
GitHub repo contributor guidelines

### ISSUE THREAD

**Issue by NoraLoose** [leap-stc/ClimSim#62]
Can we agree on the following guidelines for how to contribute to this GitHub repo?

- [x] Please always open a PR. No direct pushing to `main`.
- [x] Please leave your PRs open for other contributors to review before merging it. I think it is good practice to have other people merge your PRs (unless it is a really small change; if so please note this when merging).

I'm tagging the currently main contributors to this repo. Please give a thumbs-up if you agree to these guidelines. @jerrylin96 @cisaacstern @NoraLoose

**Comment by cisaacstern** [comment]
Just throwing it out there, both of those guidelines can be enforced programmatically by GitHub [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) that could be applied to `main` (PR required, review required, etc.).

Not to assume we can't also have "voluntary compliance" 😆 but actually such rules can be helpful for (a) remembering to re-enforce good habits; and (b) prevent mistakes (e.g., pushing to main from the terminal accidentally).

**Comment by jerrylin96** [comment]
Just happened to see this. Agree with all the suggestions here. I'm okay with programmatic enforcement, and I apologize for pushing to main / merging my own pull requests.

**Comment by jerrylin96** [comment]
Added a GitHub branch protection rule that enforces pull requests. We can add more if you'd like.

@NoraLoose @cisaacstern

**Comment by cisaacstern** [comment]
Thanks Jerry! That's great.
