### ISSUE TITLE
Cosmetic: Remove navbar

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/ClimSim#8]
When opening our [website](https://leap-stc.github.io/ClimSim/intro.html) in a full width window, we currently get this pretty useless navbar:
<img width="1192" alt="image" src="https://github.com/leap-stc/ClimSim/assets/14314623/723c40c3-4e1c-447f-b703-2879a3183c95">

Would be nice to remove that entirely or at least toggle it to hidden by default. 

I am pretty sure we could achieve this with some advanced html/css stuff in [JupyterBook](https://jupyterbook.org/en/stable/advanced/html.html), but I did not get this to work quickly.

**Comment by NoraLoose** [comment]
Resolved via #32

**Comment by NoraLoose** [comment]
Resolved via https://github.com/leap-stc/ClimSim/pull/32
