### ISSUE TITLE
Issue on page /quickstart.html

### ISSUE THREAD

**Issue by jerrylin96** [leap-stc/ClimSim#82]
For some reason edits to the quickstart.md aren't showing up on the website. Do you know what's going on?

**Comment by jbusecke** [comment]
I am not sure what edits you are referring to? Can you post a link to a commit/PR?

Ok I see that the latest [CI](https://github.com/leap-stc/ClimSim/actions/runs/8677058712/job/23792226428) failed. This seems to be related to version conflict in the upload/download github action. Gimme a sec to activate dependabot to avoid this in the future.

**Comment by jbusecke** [comment]
@jerrylin96 how active are people still working on the docs here? If a lot it might be worth refactoring the website build (this would be a considerable amount of work). 

Assuming #83  and the updates in #84, #85, #86, #87, #88 fix this problem it might be better to just keep as is, but LMK.

In general to debug this I recommend checking that [This Workflow](https://github.com/leap-stc/ClimSim/actions/workflows/publish-website.yml) is succeeding!

**Comment by jbusecke** [comment]
Unfortunately the changes did not fix this 😩. Trying to come up with a fix in #89

**Comment by jbusecke** [comment]
Ok I think #89 is fixing this. Can you confirm that the website is not reflecting what you expect and let me know in #89 so I can merge?

**Comment by jbusecke** [comment]
Closed via #89
